development:
  bucket: ceheroku-uploads
  access_key_id: '<%= ENV["S3_KEY"] %>'
  secret_access_key: '<%= ENV["S3_SECRET"] %>'
  use_persistent: false

test:
  bucket: ceheroku-uploads
  access_key_id: '<%= ENV["S3_KEY"] %>'
  secret_access_key: '<%= ENV["S3_SECRET"] %>'
  use_persistent: false

production:
  bucket: ceheroku-uploads
  access_key_id: '<%= ENV["S3_KEY"] %>'
  secret_access_key: '<%= ENV["S3_SECRET"] %>'
  use_persistent: false